stages:        
  - test


int-test-job:   
  stage: test    
  script:
    - echo "hello world"
  artifacts:
    when: always
    paths:
      - code/output-2022-14-11-17-46.xml
    reports:
      junit: code/output-2022-14-11-17-46.xml
