PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?property ?inverse
WHERE {
  ?property a owl:SymmetricProperty.
  {?inverse owl:inverseOf ?property.} UNION {?property owl:inverseOf ?inverse.}.
}
