PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?p ?type
WHERE {
  VALUES ?type {owl:ObjectProperty owl:DatatypeProperty}.
  ?p a ?type.
  # Subquery where range is missing
  {
    SELECT ?p
    WHERE {
      ?p a ?type.
      ?p rdfs:domain ?d.
      FILTER NOT EXISTS{?p rdfs:range ?r}. 
    }
  }
  UNION
  # Subquery where domain is missing
  {
    SELECT ?p
    WHERE {
      ?p a ?type.
      ?p rdfs:range ?r.
      FILTER NOT EXISTS{?p rdfs:domain ?d}. 
    }
  }
  UNION
  # Subquery where domain and range are missing
  {
    SELECT ?p
    WHERE {
      ?p a ?type. 
      FILTER NOT EXISTS{?p rdfs:domain ?d. 
        ?p rdfs:range ?r. }.  
    }
  }
}
 