PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX cc: <http://creativecommons.org/ns#>


SELECT ?ontology
WHERE{
  ?ontology a owl:Ontology.
  FILTER NOT EXISTS{ {?ontology dc:rights ?license.} UNION {?ontology dcterms:license ?license.} UNION {?ontology schema:license ?license.} UNION {?ontology cc:license ?license}.}
}
