PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT DISTINCT ?label
WHERE {
  ?c1 rdf:type owl:Class.
  ?c2 rdf:type owl:Class.
  ?c1 rdfs:label ?label.
  ?c2 rdfs:label ?label.
  FILTER (?c1 != ?c2).
}
